### PR TITLE
Explicitly call out that reuse is not implemented yet.

### LINKED ISSUE #170: "Using the Engine" documentation is incorrect

### PR DESCRIPTION
**Pull request by zachnew-msft**
Resolves #170

### CODE REVIEW

**Review by jmaxson-ms — APPROVED** [review]

**Review by mslukebo — DISMISSED** [review]

**Comment by mslukebo** [comment]
@zachnew-msft the paragraph starting "Finally, you can specify that the `DataSourceSet` should take ownership of the" is also not correct

**Review by mslukebo — DISMISSED** [review]
Need to update the "you can specify that the DataSourceSet should take ownership" paragraph

**Comment by zachnew-msft** [comment]
> @zachnew-msft the paragraph starting "Finally, you can specify that the `DataSourceSet` should take ownership of the" is also not correct

I have a note right after it that it is not fully implemented and false is not supported. The API is there.

**Comment by mslukebo** [comment]
> > @zachnew-msft the paragraph starting "Finally, you can specify that the `DataSourceSet` should take ownership of the" is also not correct
> 
> I have a note right after it that it is not fully implemented and false is not supported. The API is there.

Sorry I referenced the wrong part. The sentences beginning with "Similar to how the `DataSourceSet`
can take ownership of the `PluginSet`, the `Engine` takes ownership of the
`DataSourceSet`." is incorrect. It references EngineCreateInfo.OwnsDataSource, which does not exist

**Comment by zachnew-msft** [comment]
> > > @zachnew-msft the paragraph starting "Finally, you can specify that the `DataSourceSet` should take ownership of the" is also not correct
> > 
> > 
> > I have a note right after it that it is not fully implemented and false is not supported. The API is there.
> 
> Sorry I referenced the wrong part. The sentences beginning with "Similar to how the `DataSourceSet` can take ownership of the `PluginSet`, the `Engine` takes ownership of the `DataSourceSet`." is incorrect. It references EngineCreateInfo.OwnsDataSource, which does not exist

Thanks! I will fix it.

**Review by mslukebo — APPROVED** [review]
Self-approving since most of this was written by someone else 😄

**Review by jmaxson-ms — APPROVED** [review]
:shipit:

**Pull request merged**
